### ISSUE TITLE
Improve utils.go

### ISSUE THREAD

**Issue by stevenlcf** [joincivil/go-common#35]
Here are one bug report and one improvement request for [go-common/pkg/eth/utils.go](https://github.com/joincivil/go-common/blob/42b705b5ae51e5ce9dd7b45f6a9eab7c27d6d7a6/pkg/eth/utils.go):

#### Bug report:
* [This line](https://github.com/joincivil/go-common/blob/42b705b5ae51e5ce9dd7b45f6a9eab7c27d6d7a6/pkg/eth/utils.go#L79) in utils.go doesn't link all libraries (i.e. replace with library address in the bytecode) but only link the last one in the map.

#### Improvement request:
* Make `DeployContractWithLinks` function accept `params ...interface{}` in the input for the potential parameters in the deploying contract's constructor.

**Comment by petersng** [comment]
Thanks for the PR with these fixes and improvements.  We'll take a look at it.
